server:
  port: 8888
spring:
  application:
    name: camel-training-project
  profiles:
    active: local

camel:
  springboot:
    main-run-controller: true
    name: ServicesRest
#management:
#  port: 8081
#endpoints:
#  enabled: false
#  health:
#    enabled: true
#quickstart:
#  generateOrderPeriod: 5s
#  processOrderPeriod: 5s
ftp:
  server: ftp://localhost:21?username=thachhuynh&password=bathach1995